### PR TITLE
fix bug of "can't load css file"

### PR DESCRIPTION
**Pull request by FrozenKP**
fix the URL of css file.

### CODE REVIEW

**Comment by adambabik** [comment]
It's not a good approach because if you access `alpha.html` via HTTPS, modern browsers will reject these HTTP calls. 

Can you provide more details how you get `can't load css file` error?

**Comment by FrozenKP** [comment]
Hi, I found that it can’t load CSS file when I open it directly. CSS file is opened from “file://…” . It worked fine when I make it a real website. I think that when using “/…” is not convenient enough for users to check the site status now when editing.

**Comment by adambabik** [comment]
If you opened that HTML file directly in a browser using `file://` scheme, then it's a normal behavior because `//` reuses document's scheme. I recommend opening HTML pages using a local server. E.g. you can run `python -m SimpleHTTPServer 8000` in a directory where your HTML pages are located and you can see them opening http://localhost:8000/page.html.

**Comment by FrozenKP** [comment]
Got it.

**Pull request closed without merging**
